language: android
jdk: oraclejdk8
before_install:
 - chmod +x gradlew
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - addon-google_apis-google-26

    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-android-17
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'